name: snake
channels:
  - anaconda
dependencies:
  - python=3.6
  - pip
  - pip:
    - pygame==2.0.0.dev6
    - dataclasses==0.8
    - sympy==1.9
    - mpmath==1.2.1
    - psutil==5.9.0
    - numpy==1.19.5